Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Models/Classes/Pagina.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab_04_JosueHigueros_PabloAlvarado.Models.Classes
{
    public class Pagina
    {
        public List<int> faltantes { get; set; }
        public List<int> coleccionadas { get; set; }
        public List<int> cambios { get; set; }
    }
}

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Controllers/PaginaController.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace Lab_04_JosueHigueros_PabloAlvarado.Models.Classes
{
    public class PaginaController : Controller
    {
        // GET: Pagina
        public ActionResult Index(Pagina ValorBuscado)
        {
            List<Pagina> Lista = new List<Pagina>();
            List<string> Nombres = new List<string>();
            
            if(ValorBuscado.coleccionadas == null)
            {
                foreach (var item in DataBase.Instance.Diccionario1)
                {
                    Lista.Add(item.Value);
                    Nombres.Add(item.Key);
                }
                return View(Lista);
            }
            else
            {
                Lista.Add(ValorBuscado);
                return View(Lista);
            }
           
          
        }


        // GET: Pagina
        public ActionResult IndexEstampa(List<Estampa> Busqueda)
        {
            if(Busqueda == null)
            {
                List<Estampa> ListadeEstampas = new List<Estampa>();
                foreach (var item in DataBase.Instance.Diccionario2)
                {
                    ListadeEstampas.Add(item.Value);
                }
                return View(ListadeEstampas);
            }
            else
            {
                return View(Busqueda);
            }
            
        }
        

       // GET: Pagina
       public ActionResult Modificar(string Nombre, int Numero, bool Obtenida)
        {
            Estampa Auxiliar = new Estampa();
            Auxiliar.Nombre = Nombre;
            Auxiliar.Numero = Numero;
            Auxiliar.Obtenida = Obtenida;
            //Hola

            foreach (var item in DataBase.Instance.Diccionario2)
            {
                if(Auxiliar.Nombre == item.Value.Nombre)
                {
                    if(Auxiliar.Numero == item.Value.Numero)
                    {
                        item.Value.Obtenida = Obtenida;
                    }
                }
            }
            return View();
           
        }

        // GET: Pagina/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pagina/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pagina/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagina/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pagina/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagina/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pagina/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Busqueda(string Tipo, string Search)
        {

            Pagina ValorBuscado = new Pagina();
            if (Tipo == null && Search == null)
            {
                return View("Busqueda");
            }
            foreach (var item in DataBase.Instance.Diccionario1)
            {
                if (item.Key == Search)
                {
                    ValorBuscado.cambios = item.Value.cambios;
                    ValorBuscado.coleccionadas = item.Value.coleccionadas;
                    ValorBuscado.faltantes = item.Value.faltantes;
                    ViewBag.Message = item.Key;
                }

            }

            if(ValorBuscado.cambios != null && ValorBuscado.coleccionadas != null && ValorBuscado.faltantes != null)
            {
                List<Pagina> Lista = new List<Pagina>();
                Lista.Add(ValorBuscado);
                return View("Index", Lista);
            }
            else
            {
                TempData["msg"] = "<script> alert('Dato No Encontrado');</script>";
                return View("Busqueda");
            }
            
        }

        public ActionResult BusquedaII(FormCollection collection)
        {

            Estampa ValorBuscado = new Estampa();
            if (collection["Pais"] == null && collection["Numero"] == null)
            {
                return View("BusquedaII");
            }
            foreach (var item in DataBase.Instance.Diccionario2)
            {
                string Auxiliar = (collection["Pais"] + "_" + collection["Numero"]);
                Auxiliar = " " + Auxiliar;
                if (collection["Pais"] == "Especial")
                {
                    if (item.Key == collection["Pais"] + collection["Numero"])
                    {
                        ValorBuscado.Nombre = collection["Pais"];
                        if (item.Value.Numero == int.Parse(collection["Numero"]))
                        {
                            ValorBuscado.Numero = int.Parse(collection["Numero"]);
                            ValorBuscado.Obtenida = item.Value.Obtenida;
                        }
                    }
                }
                else if (item.Key == Auxiliar)
                {
                    ValorBuscado.Nombre = collection["Pais"];
                    if (item.Value.Numero == int.Parse(collection["Numero"]))
                    {
                        ValorBuscado.Numero = int.Parse(collection["Numero"]);
                        ValorBuscado.Obtenida = item.Value.Obtenida;
                    }
                }

            }

            if(ValorBuscado.Nombre != null && ValorBuscado.Numero == int.Parse(collection["Numero"]))
            {
                List<Estampa> Lista = new List<Estampa>();
                Lista.Add(ValorBuscado);
                return View("IndexEstampa", Lista);
            }
            else
            {
                TempData["msg1"] = "<script> alert('Dato No Encontrado');</script>";
                return View("BusquedaII");
            }

        }

        public ActionResult UploadFileEstampa()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Aca se hace el Ingreso por medio de Archivo de Texto, ya que el Boton de Result esta Linkeado.
        public ActionResult UploadFileEstampa(HttpPostedFileBase file)
        {

            if (Path.GetExtension(file.FileName) != ".json")
            {
                //Aca se debe de Agregar una Vista de Error, o de Datos No Cargados
                return RedirectToAction("Error", "Shared");
            }

            Stream Direccion = file.InputStream;
            //Se lee el Archivo que se subio, por medio del Lector

            StreamReader Lector = new StreamReader(Direccion);
            string Temp = Lector.ReadToEnd();
            //El Archivo se lee en una lista para luego ingresarlo
            Dictionary<string, Estampa> Diccionario = new Dictionary<string, Estampa>();

            Temp = Temp.TrimStart('{');
            var Temporal = Temp.Split(',');
            List<Estampa> ListadeEstampas = new List<Estampa>();
           
            foreach (var item in Temporal)
            {
                if(item.Contains("Especial"))
                {
                    Estampa Auxiliar1 = new Estampa();
                    Auxiliar1.Nombre = "Especial";
                    if(item.Contains("true"))
                    {
                        Auxiliar1.Obtenida = true;
                    }
                    else
                    {
                        Auxiliar1.Obtenida = false;
                    }
                    var temporal = item.Remove(1, 8);
                    var numero = temporal.Split(':');
                    numero[0] = numero[0].Replace('{', ' ');
                    numero[0] = numero[0].Replace('"', ' ');
                    Auxiliar1.Numero = int.Parse(numero[0]);
                    Diccionario.Add(Auxiliar1.Nombre+Auxiliar1.Numero, Auxiliar1);

                }
                else
                {

                    Estampa Auxiliar2 = new Estampa();
                    if (item.Contains("true"))
                    {
                        Auxiliar2.Obtenida = true;
                    }
                    else
                    {
                        Auxiliar2.Obtenida = false;
                    }
                    var ArregloTemporal = item.Split(':');
                    var AuxiliarNombre = ArregloTemporal[0];
                    var ArregloTemporalNombre = AuxiliarNombre.Split('_');
                    ArregloTemporalNombre[0] = ArregloTemporalNombre[0].Replace('"', ' ');
                    ArregloTemporalNombre[1] = ArregloTemporalNombre[1].Replace('"', ' ');
                    Auxiliar2.Nombre = ArregloTemporalNombre[0];
                    Auxiliar2.Numero = int.Parse(ArregloTemporalNombre[1]);
                    Diccionario.Add(Auxiliar2.Nombre+"_"+Auxiliar2.Numero, Auxiliar2);
                }

            }

            DataBase.Instance.Diccionario2 = Diccionario;
            return RedirectToAction("IndexEstampa");

        }


        public ActionResult UploadFile()
        {
            return View();
        }

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/Busqueda.cshtml
@model IEnumerable<Lab_04_JosueHigueros_PabloAlvarado.Models.Classes.Pagina>

@{
    ViewBag.Title = "Busqueda";
}

@Html.Raw(TempData["msg"])
<h2>Busqueda</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div id="contenedor"></div>
        <h4>Seleccione una Opcion para Buscar</h4>
        <form method="get" action="@Url.Action("Busqueda", "Pagina")">
            <label for="search">Buscar Por:</label>
            <select name="Tipo" id="Tipo">
                <option value="Pais">Pais</option>
            </select>
            <input type="text" name="Search" id="Search" />
            <button type="submit">Buscar</button>
        </form>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/BusquedaII.cshtml
@model Lab_04_JosueHigueros_PabloAlvarado.FilterConfig

@{
    ViewBag.Title = "Busqueda";
}

@Html.Raw(TempData["msg1"])

<h2>Busqueda</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Busqueda Diccionario II</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("País", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.Editor("Pais", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Número", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.Editor("Numero", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <p align="center"><input type="submit" value="Buscar" class="btn btn-default" /></p>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al Album", "IndexEstampa")
</div>

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/Index.cshtml
@model IEnumerable<Lab_04_JosueHigueros_PabloAlvarado.Models.Classes.Pagina>

@{
    ViewBag.Title = ViewBag.Message;
}

<h2>@ViewBag.Message</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Coleccionadas:
        </th>
        <th>
            Cambios:
        </th>
        <th>
            Faltantes:
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
           @for (int i = 0; i < item.coleccionadas.Count; i++)
           {
             @Html.DisplayFor(modelItem => item.coleccionadas[i]);

               if(i != item.coleccionadas.Count-1)
               {
                   <a>-</a>
               }
           }
        </td>
        <td>
            @for (int i = 0; i < item.cambios.Count; i++)
           {
               @Html.DisplayFor(modelItem => item.cambios[i]);

               if(i != item.cambios.Count-1)
               {
                   <a>-</a>
               }
           }
        </td>
        <td>
            @for (int i = 0; i < item.faltantes.Count; i++)
           {
              @Html.DisplayFor(modelItem => item.faltantes[i]);

               if(i != item.faltantes.Count-1)
               {
                   <a>-</a>
               }
           }
        </td>
        <td>
        <td>
            @Html.ActionLink("Modificar", "Modificar", new {NuevaPaginai = Model, Mensaje = ViewBag.Message})
        </td>
    </tr>
    }

</table>

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/IndexEstampa.cshtml
@model IEnumerable<Lab_04_JosueHigueros_PabloAlvarado.Models.Classes.Estampa>

@{
    ViewBag.Title = "Diccionario 2";
}

<h2>Album Panini 2018</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Obtenida)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Numero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Obtenida)
        </td>
        <td>
            @Html.ActionLink("Editar", "Modificar", new {Nombre = item.Nombre, Numero = item.Numero, Obtenida = item.Obtenida})
        </td>
    </tr>
}

</table>

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/Modificar.cshtml
@model Lab_04_JosueHigueros_PabloAlvarado.Models.Classes.Estampa

@{
    ViewBag.Title = "Modificar";
}

<h2>Modificar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estampa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obtenida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Obtenida)
                    @Html.ValidationMessageFor(model => model.Obtenida, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cambiar Estado" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/UploadFile.cshtml
@{
    ViewBag.Title = "Cargar Archivo";
}

<h2>Subir Archivo</h2>
@using (Html.BeginForm("UploadFile", "Pagina", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary();

    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 align="center">Agregar con Archivo</h2>
            <p align="center">
                Para agregar Estampitas a través de un archivo .json
            </p>

            <div align="center" class="form-group">
                <input type="file" name="file" value="Examinar" class="btn-default" style="color:transparent" />
            </div>
            <div align="center" class="form-group">
                <button type="submit" class="btn btn-default">Subir archivo</button>
            </div>

        </div>
    </div>
}

Lab_04_JosueHigueros_PabloAlvarado/Lab_04_JosueHigueros_PabloAlvarado/Views/Pagina/UploadFileEstampa.cshtml
@{
    ViewBag.Title = "Cargar Archivo";
}

<h2>Subir Archivo</h2>
@using (Html.BeginForm("UploadFileEstampa", "Pagina", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary();

    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 align="center">Agregar con Archivo</h2>
            <p align="center">
                Para agregar Estampitas a través de un archivo .json
            </p>

            <div align="center" class="form-group">
                <input type="file" name="file" value="Examinar" class="btn-default" style="color:transparent" />
            </div>
            <div align="center" class="form-group">
                <button type="submit" class="btn btn-default">Subir archivo</button>
            </div>

        </div>
    </div>
}